### PR TITLE
Kids dont wear nametags

### PR DESCRIPTION
**Pull request by hlwill**

### CODE REVIEW

**Comment by hlwill** [comment]
There's also a thing about escorting kids to the bathroom - which was more relevant when we were in the old location - what do you think about removing?

**Comment by Trappertrunk** [comment]
Hi Helen, I agree was more of an issue in old building but I think very  young children should maybe go along to loo with parents? The toilet is outside the room and, if events are on then anyone can have access, not people know to Prewired.I think also we should have some sort of 'mentors will never" guidelines, like ask for email, contact you privately on social media or whatever +age appropriate if course) we could have a look at current Coderdojo guidelines as we did afoot them ages ago (removing name badge thing if that came from there)? Just arrived Waverley :)FredaOn 15 Feb 2017 6:18 pm, Helen Williams <notifications@github.com> wrote:There's also a thing about escorting kids to the bathroom - which was more relevant when we were in the old location - what do you think about removing?

**Comment by hlwill** [comment]
Yes, this section is guidelines solely for the duty mentor.
We already have a mentors will never section that states that

**Comment by Trappertrunk** [comment]
Coolio. On 15 Feb 2017 6:34 pm, Helen Williams <notifications@github.com> wrote:Yes, this section is guidelines solely for the duty mentor.
We already have a mentors will never section that states that

**Comment by ewan-klein** [comment]
Resolved in 2fa06ce..4a84a60

**Pull request closed without merging**
